# Generated by Django 2.2.9 on 2020-02-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App2', '0002_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_name', models.CharField(max_length=16)),
                ('o_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
