# Generated by Django 2.2.9 on 2020-02-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App2', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='p_delete',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='p_sex',
            field=models.BooleanField(db_column='sex', default=True),
        ),
    ]
